# Use an official Python runtime as a parent image
FROM python:3.10.0rc2-buster

# Set the working directory in the container to /app
WORKDIR /app

# Add the current directory contents into the container at /app
ADD . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Install unixODBC driver
RUN apt-get update && apt-get install -y \
    unixodbc-dev \
    g++ \
    && apt-get clean;

# Install Microsoft ODBC 18 for SQL Server
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
    && curl https://packages.microsoft.com/config/debian/10/prod.list > /etc/apt/sources.list.d/mssql-release.list \
    && apt-get update \
    && ACCEPT_EULA=Y apt-get install -y msodbcsql18 \
    && apt-get clean;




# Make port 80 and 443 available to the world outside this container
EXPOSE 80
EXPOSE 443

# Run app.py when the container launches
CMD ["python", "app.py"]
